[package]
name = "xerox_6605_export"
version = "0.1.0"
authors = ["Tyler Hill <tyler.hill@xerox.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chttp = "0.5.3"
scraper = "0.15.0"
csv = "1.1.1"